/*1- Verificador de CPF
Todo CPF tem 11 digitos.
Os dois últimos são digitos verificadores, calculados com base nos 9 primeiros.
O calculo dos digitos usa uma formula:
Para o primeiro digito:
Multiplique cada um dos 9 primeiros digitos por 10 a 2
Some o resultado total
divida por 11, considere apenas o resto da divisao
Se o resto da divisão for menor que 2, então o dígito é igual a 0 (Zero).
Se o resto da divisão for maior ou igual a 2, então o dígito verificador é igual a 11 menos o resto da divisão (11 - resto).
Para o segundo digito:
Faça o mesmo, porém multiplicando de 11 a 2*/
